version: '3.7'

services:
  portainer:
    image: portainer/portainer:1.23.2
    volumes:
      - portainer:/data
    environment:
      AGENT_SECRET: 0c41adac4dc4923b6878ad764b4a6f29
    networks:
      - public
      - portainer
    ports:
      - target: 9000
        published: ${PORTAINER_PORT:-9000}
        mode: host

  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_SECRET: 0c41adac4dc4923b6878ad764b4a6f29
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

volumes:
  portainer:

networks:
  public:
    external: true
  portainer:
    internal: true